export interface Food {
    aggregateLikes: number,
    analyzedInstructions: [],
    title: string,
    cheap: boolean,
    cookingMinutes: number,
    cuisines: [],
    dairyFree: boolean,
    diets: [],
    dishTypes: [],
    extendedIngredients:Ingredients[],
    gaps: string,
    id: number,
    glutenFree: boolean,
    healthScore: boolean,
    instructions: string,
    lowFodmap: boolean,
    occasions: [],
    openLicense: number,
    preparationMinutes: number,
    pricePerServing: number,
    readyInMinutes: number,
    servings: number,
    sourceName: string,
    sourceUrl: string,
    spoonacularSourceUrl: string,
    summary: string,
    sustainable: boolean,
    vegan: boolean,
    vegetarian: boolean,
    veryHealthy: boolean,
    veryPopular: boolean,
    weightWatcherSmartPoints: number,
    image: string,
}

export interface Ingredients {
    id: number,
    name: string,
    nameClean: string,
    aisle: string,
    amount: number,
    consistency: string,
    image: string,
    meta: [],
    original: string,
    originalName: string,
    unit: string
}